# Netlify Configuration for React SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  VITE_SERVER_URL = "https://abjee-travel.onrender.com"
  VITE_FIREBASE_API_KEY = "AIzaSyD2RQGDQWj6uv5zZfcNOwjbi8wX6vv61Ss"
  VITE_FIREBASE_AUTH_DOMAIN = "abjee-travel-4fc38.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "abjee-travel-4fc38"
  VITE_FIREBASE_STORAGE_BUCKET = "abjee-travel-4fc38.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "1042055167342"
  VITE_FIREBASE_APP_ID = "1:1042055167342:web:4c9e26116cd60e9459d57f"
  VITE_FIREBASE_MEASUREMENT_ID = "G-VCZ3KW7NY1"
